### ISSUE TITLE
Bulk mode not working with log4net 1.2.15

### ISSUE THREAD

**Issue by PaulDMendoza** [varshneyjayant/log4net-loggly#24]
I just downloaded the latest version of Loggly and Bulk mode doesn't seem to work with log4net 1.2.15. Not sure why. When I used the flag

`<logMode value="inputs" />`

it seems to work again.

**Comment by psquickitjayant** [comment]
will check it and see what is happening there,

**Comment by lukeivers** [comment]
So just to add to this, in order to get my appender working, I had to use the following configuration:

`
<appender name="LogglyAppender" type="log4net.loggly.LogglyAppender, log4net-loggly">
      <rootUrl value="https://logs-01.loggly.com/inputs/" />
      <logMode value="inputs" />
      <inputKey value="YOUR TOKEN" />
      <tag value="log4net" />
    </appender>
`

Using just `<logMode value="inputs" />` didn't work.  I had to put /inputs/ on the URL, but if I don't ALSO use the inputs logMode, then it appends multiple events in a single large event.

This is using 7.2.1

**Comment by psquickitjayant** [comment]
Are you sure you are using the correct version? You need not to use inputs in the rootUrl. See https://github.com/psquickitjayant/log4net-loggly/commit/898f78ef9d8092129cefbf0998f2373c62a66c4c

**Comment by lukeivers** [comment]
Yep, certain.  I tried every sub-combination I could think of (just using logMode line, just setting the URL) and nothing worked properly except both setting the logMode AND putting it in the URL.

I know that's weird, I looked at the code.  Clearly setting logMode to inputs did SOMETHING, because without that line, it does send them, but it mixes up the bulk method of transfer with the inputs URL.

But if I do just the logMode thing, it just fails to log.

**Comment by lukeivers** [comment]
It turns out that somehow it was using a previous version, despite every single thing I could find indicating that it was using the newer one.  My bad.

**Comment by psquickitjayant** [comment]
so now, everything is working fine @lukeivers ?

**Comment by lukeivers** [comment]
Yes, now if I use logMode I no longer have to append inputs to the URL.  Although, I'm no longer using 1.2.15.0, I'm using 1.2.13.0 (picked up as a dependency of log4net-loggly, I'm not using log4net for anything else)
